ipc = on
splash = false

preload = /home/madeinshinea/.config/hypr/walls/wall2.jpg

wallpaper {
    monitor = eDP-1
    path = /home/madeinshinea/.config/hypr/walls/wall2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/madeinshinea/.config/hypr/walls/wall2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/madeinshinea/.config/hypr/walls/wall2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/madeinshinea/.config/hypr/walls/wall2.jpg
    fit_mode = cover
}
